name: qrcodegenerator
services:
    qrc_gen:
        container_name: qrc_gen
        image: zauberzeug/nicegui
        build: 
            dockerfile: Dockerfile
        restart: always
        ports:
            - 8080:8080
        volumes:
            - ./:/app/
        command: ./start.sh prod
